### ISSUE TITLE
Encoding error after processing docx file in JSZip 3.x -> same code works in JSZip 2.x

### ISSUE THREAD

**Issue by patrick904** [Stuk/jszip#403] opened 2017-03-08 13:26 UTC
In JSZip 3.x ew get encoding errors from Microsoft Word (docx) after replacing placeholder in word/document.xml files. Same Code works just fin with JSZip 2.x

Documents containing characters like ö,ü,ä,ß will cause an error in Microsoft Word -> invalid XML character on line 2, column 2437 in JSZip 3.x. Same document with JSZip 2.x works fine: no errors, characters like ö.ä.ü,ß are processed asa well.

[document.txt](https://github.com/Stuk/jszip/files/827699/document.txt)

**Comment by dduponchel** [comment] 2017-03-08 19:48
It seems this file isn't encoded in UTF-8. For example, `Köln` isn't encoded as `4B C3 B6 6C 6E` ([ö is `0xC3 0xB6` in unicode](http://www.fileformat.info/info/unicode/char/f6/index.htm)) but as `4B F6 6C 6E` ([ö is `0xF6` in ISO-8859-1](http://www.fileformat.info/info/charset/ISO-8859-1/list.htm)).

I tested with JSZip v2 and v3: both corrupt the data when decoding/encoding this file. How do you manipulate this file in v2 and in v3 ?

**Comment by patrick904** [comment] 2017-03-09 12:04
Hi,

 

thanky for your replay.

 

The document is create with Microsoft Word 2010 and saved in docx format.

 

Here my code with JSZip 3 (latest Verion from nuget)

 


JSZipUtils.getBinaryContent(url, function (err, data) {
                if (err) {
                    console.log(err);
                    return;
                }
                JSZip.loadAsync(data).then(function (zip) {
                    return zip;
                }).then(function (zip) {

                    var contentPromise = zip.file("word/document.xml").async("string").then(function (content) {
                        return content.replace(pattern, function (match, key) {
                            return replaceData[key];
                        });
                    });
                    zip.file("word/document.xml", contentPromise, {optimizedBinaryString: true});

                    zip.generateAsync({ type: 'blob' }).then(function (blob) {
                        saveAs(blob, "test2.docx", true);
                    });
                    //zip.generateAsync({ type: "uint8array" }).then(function(fileContent){
                    //    try{
                    //        var clientContext = new SP.ClientContext.get_current();
                    //        var spWeb = clientContext.get_web();
                    //        var docList = spWeb.get_lists().getByTitle("Briefvorlagen");
                    //        var ci = new SP.FileCreationInformation();
                    //        ci.set_url("test2.docx");
                    //        ci.set_overwrite(true);
                    //        ci.set_content(new SP.Base64EncodedByteArray());
                    //        for (var i = 0; i < fileContent.length; i++) {
                    //            ci.get_content().append(fileContent[i]);
                    //        }
                    //        var newFile = docList.get_rootFolder().get_files().add(ci);
                    //        clientContext.load(spWeb);
                    //        clientContext.load(newFile);
                    //        clientContext.executeQueryAsync(function () {
                    //            console.log('Erfolg.');
                    //        }, function () {
                    //            console.log(arguments[1].get_message());
                    //        });
                    //    }
                    //    catch (e) {
                    //        console.log(e);
                    //    }
                    
                    });

                });
            });

 

Both results - saveAs and creating the new document in a SharePoint Library - are invalid.

 

Here my code with JSZip 2 (latest Verion from nuget)


JSZipUtils.getBinaryContent(url, function (error, data) {

                    if (error) {
                        console.log(error);
                        return;
                    }
                    var zip = new JSZip(data);
                    var content = zip.file("word/document.xml").asText();

                    content = content.replace(pattern, function (match, key) {
                        return replaceData[key];
                    });

                    zip.file("word/document.xml", content);

                    saveAs(zip.generate({ type: 'blob' }), "test42.docx");

 

The same docx document without any errors.

 

Kind regarts

Patrick



Gesendet: Mittwoch, 08. März 2017 um 20:48 Uhr
Von: "David Duponchel" <notifications@github.com>
An: Stuk/jszip <jszip@noreply.github.com>
Cc: patrick904 <patrick.schutte@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [Stuk/jszip] Encoding error after processing docx file in JSZip 3.x -> same code works in JSZip 2.x (#403)


It seems this file isn't encoded in UTF-8. For example, Köln isn't encoded as 4B C3 B6 6C 6E (ö is 0xC3 0xB6 in unicode) but as 4B F6 6C 6E (ö is 0xF6 in ISO-8859-1).

I tested with JSZip v2 and v3: both corrupt the data when decoding/encoding this file. How do you manipulate this file in v2 and in v3 ?

**Comment by dduponchel** [comment] 2017-03-09 18:23
It looks like the bug #325. Could you remove `optimizedBinaryString` (it's a string, not a binary string) and use `binary` instead ?

```js
zip.file("word/document.xml", contentPromise, {binary: false});
```

**Comment by gpalomar** [comment] 2017-07-19 09:43
Same problem here. Using JSZip 3.1.3.

I'm trying to generate a ZIP with a folder and two files inside it (one of them is a .docx file) and my downloaded zip name looks like this --> **[_folder_name_].zip.cpgz**
If I try the same using non .docx files, it works fine.

I have tried to use a different way to attach the file (changing binary: true/false) and different output (uint8array and blob) but still getting the same problem 😞 

In my case I don't set the binary content using a promise.

Anyone with the same annoying issue?

**Comment by dduponchel** [comment] 2017-08-19 18:18
I'm closing this issue as a duplicate of #325.

@gpalomar your issue seems different (you include a docx file, not generating one). Could you open a new issue with your code ?

**Closed by dduponchel** 2017-08-19 18:18 UTC

**Comment by anilsambasivan** [comment] 2020-12-09 10:57
The below code worked for me

d.zip.loadAsync(blob).then(z => {
            var f = d.zip.files[PartType.Document];
            f ? f.async("text").then(xml => {
               
                var result = new DOMParser().parseFromString(xml, "application/xml");
               
                var xmlString = new XMLSerializer().serializeToString(result);
                d.zip.file("word/document.xml", xmlString);
                z.generateAsync({type:"blob"}).then(x=> {
                    saveAs(x, "test.docx")
                });
            }) : null;
        });
