### ISSUE TITLE
ADD: Documentation Example 

### ISSUE THREAD

**Issue by Aqua-4** [Stuk/jszip#695] opened 2020-07-14 11:07 UTC
# FIX: Error: Invalid base64 input, it looks like a data url.

## Example on how to work with canvas images.

code:
`
  var zip = new JSZip();
  var img = zip.folder("images");
  html2canvas(document.querySelector("#chart_placeholder_0")).then(canvas => {
    img.file("imr.png", canvas.toDataURL("image/png", [0.0, 1.0]).split(',')[1], { base64: true });
  });
  zip.generateAsync({ type: "blob" }).then(function (content) {
    saveAs(content, "example.zip");
  });
`

**Comment by Stuk** [comment] 2020-07-15 19:41
Dupe of #694

**Closed** 2020-07-15 19:41 UTC

**Comment by sunshaobin** [comment] 2021-03-04 03:44
I have same question
